import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import toast from 'react-hot-toast'
import {
  ChartBar,
  ClipboardText,
  GearSix,
  UsersThree,
} from '@phosphor-icons/react'
import { CheckSquare } from 'lucide-react'
import api from '../api'
import { useAuth } from '../context/AuthContext'
import PulseLoading from '../components/PulseLoading'
import PulseSmartChat from '../components/PulseSmartChat'
import PulseAppearanceToggle from '../components/PulseAppearanceToggle'
import {
  dismissPulseGuide,
  getPulseGettingStartedPath,
  PULSE_HOME,
  getPulseSampleChoice,
  hasPulseAccount,
  hasPulseSampleChoice,
  markPulseAccountCreated,
  isAutoGeneratedPortalId,
  isReservedPortalSegment,
  needsPulseGettingStartedGuide,
  normalizePulsePortalId,
  portalIdFromCompanyName,
  suggestPulsePortalId,
} from '../utils/pulseEntry'
import PulseSampleDataStep from './PulseSampleData'
import './pulse-getting-started.css'
import './pulse-sample-data.css'

const INDUSTRIES = [
  'Agriculture',
  'Art, Architecture & Design',
  'Automotive',
  'Aviation / Aerospace',
  'Banking',
  'Biotechnology',
  'Chemicals',
  'Construction / Real Estate',
  'Consulting',
  'Consumer Goods',
  'E-Commerce',
  'Education',
  'Electronics',
  'Energy / Oil & Gas',
  'Entertainment / Media',
  'Finance / BFSI',
  'Food & Beverage',
  'Government / Public Sector',
  'Healthcare',
  'Hospitality / Travel',
  'Information Technology (IT)',
  'Insurance',
  'Internet / Web Services',
  'Legal',
  'Logistics / Supply Chain',
  'Manufacturing',
  'Marketing / Advertising',
  'Mining / Metals',
  'Non-profit / NGO',
  'Pharmaceuticals',
  'Product / SaaS',
  'Retail',
  'Software Development',
  'Software / Technology',
  'Startups',
  'Telecom',
  'Technology / IT Services',
  'Textiles / Apparel',
  'Transportation',
  'Utilities',
  'Other',
]

const WORKFLOW = [
  {
    title: 'Set up organization',
    desc: 'Configure your organization settings.',
  },
  {
    title: 'Invite users',
    desc: 'Invite people to their self-service portal.',
  },
  {
    title: 'Configure leave policies',
    desc: 'Create leave types that match your organization policies.',
  },
  {
    title: 'Define shifts',
    desc: 'Set up the shifts your organization uses.',
  },
  {
    title: 'Configure timesheet approvals',
    desc: 'Choose who approves timesheets.',
  },
]

/** Thin outline check-square (Lucide), matching the Getting Started reference. */
function WorkflowCheckIcon() {
  return (
    <CheckSquare
      className="pgs-check-ico"
      size={20}
      strokeWidth={1.75}
      aria-hidden="true"
    />
  )
}

function PulseVersionHero() {
  return (
    <div className="pgs-hero-art" aria-hidden="true">
      <img
        className="pgs-hero-img"
        src="/pulse-1-hero.png?v=2"
        alt=""
        draggable={false}
        decoding="async"
      />
    </div>
  )
}

const SLIDES = [
  {
    id: 'intro',
    kind: 'intro',
    title: (
      <>
        Introducing <strong>Pulse 1.0</strong>
      </>
    ),
    body: 'Say hello to a smoother, more organized, and sleeker experience. Crafted to deliver an enhanced workplace journey, not just for HR and managers but for all employees!',
  },
  {
    id: 'operations',
    kind: 'feature',
    title: 'Operations (For Administrators)',
    body: 'HR processes that were once scattered across modules - like data management, employee management, and appraisal cycles - are now consolidated here for a more streamlined experience.',
    visual: 'operations',
  },
  {
    id: 'reports',
    kind: 'feature',
    title: 'Reports',
    body: 'A consolidated space for all your reports! Quick access to important data is at your fingertips to help you stay in control and make clear-cut decisions.',
    visual: 'reports',
  },
  {
    id: 'myspace',
    kind: 'feature',
    title: 'My Space',
    body: 'Jump into action with what requires your focus today! Edit your profile, skim through your feeds, check in, view attendance insights, handle your approvals, and more!',
    visual: 'myspace',
  },
  {
    id: 'team',
    kind: 'feature',
    title: 'Team Space',
    body: 'Stay informed with the all-new Team Space. Designed to help teams collaborate by sharing and staying updated with a dedicated department wall. The Team tab gives you quick access to your department colleagues, project members, and reportees.',
    visual: 'team',
  },
  {
    id: 'settings',
    kind: 'feature',
    title: 'Settings (For Administrators)',
    body: 'Settings is the command center for your organization. Manage accounts, employee information, marketplace apps, and developer tools from one place.',
    visual: 'settings',
  },
]

function IndustrySelect({ value, onChange, disabled }) {
  const rootRef = useRef(null)
  const searchRef = useRef(null)
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState('')

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    if (!q) return INDUSTRIES
    return INDUSTRIES.filter((item) => item.toLowerCase().includes(q))
  }, [query])

  useEffect(() => {
    if (!open) return undefined
    const onDoc = (e) => {
      if (!rootRef.current?.contains(e.target)) setOpen(false)
    }
    const onKey = (e) => {
      if (e.key === 'Escape') setOpen(false)
    }
    document.addEventListener('mousedown', onDoc)
    document.addEventListener('keydown', onKey)
    window.setTimeout(() => searchRef.current?.focus(), 0)
    return () => {
      document.removeEventListener('mousedown', onDoc)
      document.removeEventListener('keydown', onKey)
    }
  }, [open])

  const pick = (item) => {
    onChange(item)
    setQuery('')
    setOpen(false)
  }

  return (
    <div className={`pgs-combo${open ? ' is-open' : ''}`} ref={rootRef}>
      <button
        type="button"
        className="pgs-combo-trigger"
        disabled={disabled}
        aria-haspopup="listbox"
        aria-expanded={open}
        onClick={() => {
          if (disabled) return
          setOpen((v) => !v)
          setQuery('')
        }}
      >
        <span className={value ? 'is-value' : 'is-placeholder'}>{value || 'Select'}</span>
        <i className="pgs-combo-chevron" aria-hidden="true" />
      </button>

      {open ? (
        <div className="pgs-combo-menu" role="listbox">
          <div className="pgs-combo-search">
            <svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true">
              <circle cx="11" cy="11" r="7" fill="none" stroke="currentColor" strokeWidth="2" />
              <path
                d="M16.5 16.5L21 21"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
              />
            </svg>
            <input
              ref={searchRef}
              type="search"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Search"
              aria-label="Search industries"
              autoComplete="off"
            />
          </div>
          <ul className="pgs-combo-list">
            {filtered.length === 0 ? (
              <li className="pgs-combo-empty">No matches</li>
            ) : (
              filtered.map((item) => (
                <li key={item}>
                  <button
                    type="button"
                    role="option"
                    aria-selected={item === value}
                    className={item === value ? 'is-active' : undefined}
                    onClick={() => pick(item)}
                  >
                    {item}
                  </button>
                </li>
              ))
            )}
          </ul>
        </div>
      ) : null}

      <input
        type="text"
        value={value}
        required
        tabIndex={-1}
        readOnly
        aria-hidden="true"
        className="pgs-combo-ghost"
      />
    </div>
  )
}

function SlideVisual({ type }) {
  if (type === 'operations') {
    return (
      <div className="pgs-viz pgs-viz-ops" aria-hidden="true">
        <div className="pgs-viz-toolbar">
          <span>Mass Update</span>
          <span>Trigger Onboarding</span>
          <span>Send for Signature</span>
          <span className="is-danger">Delete</span>
        </div>
        <div className="pgs-viz-table">
          <div className="pgs-viz-row is-head">
            <i />
            <b>Name</b>
            <b>Role</b>
            <b>Date of Joining</b>
          </div>
          {[
            ['Priya Sharma', 'HR Manager', '12 Jan 2024'],
            ['Aarav Mehta', 'Engineer', '03 Mar 2024'],
            ['Chloe Williams', 'Designer', '18 Jun 2023'],
          ].map(([name, role, doj], i) => (
            <div key={name} className={`pgs-viz-row${i === 2 ? ' is-on' : ''}`}>
              <i className={i === 2 ? 'is-checked' : undefined} />
              <span>
                <em />
                {name}
              </span>
              <span>{role}</span>
              <span>{doj}</span>
            </div>
          ))}
        </div>
      </div>
    )
  }

  if (type === 'reports') {
    return (
      <div className="pgs-viz pgs-viz-reports" aria-hidden="true">
        <div className="pgs-viz-card">
          <strong>Team Report</strong>
          <div className="pgs-bars">
            <i style={{ height: '52%' }} />
            <i style={{ height: '78%' }} />
            <i style={{ height: '38%' }} />
            <i style={{ height: '92%' }} />
          </div>
        </div>
        <div className="pgs-viz-card">
          <strong>Goals</strong>
          <div className="pgs-donut" />
          <ul>
            <li>Completed</li>
            <li>In-Progress</li>
            <li>Delayed</li>
          </ul>
        </div>
        <div className="pgs-viz-card is-wide">
          <strong>Organization Report</strong>
          <svg className="pgs-lines" viewBox="0 0 280 72" width="100%" height="56" preserveAspectRatio="none">
            <path
              d="M2 48 C28 46, 48 22, 78 30 S120 58, 158 34 S210 16, 248 28 S270 40, 278 36"
              fill="none"
              stroke="#7c3aed"
              strokeWidth="2.4"
              strokeLinecap="round"
            />
            <path
              d="M2 56 C32 50, 58 38, 92 44 S140 18, 178 30 S228 48, 258 34 S272 28, 278 32"
              fill="none"
              stroke="#ef4444"
              strokeWidth="2.4"
              strokeLinecap="round"
            />
          </svg>
        </div>
      </div>
    )
  }

  if (type === 'myspace') {
    return (
      <div className="pgs-viz pgs-viz-myspace" aria-hidden="true">
        <aside>
          <em />
          <strong>Jonessa Alisa</strong>
          <span>HR Manager</span>
          <button type="button" tabIndex={-1}>
            Check-Out
          </button>
        </aside>
        <div>
          <nav>
            <span>Activities</span>
            <span>Feeds</span>
            <span className="is-on">Career History</span>
            <span>Attendance</span>
          </nav>
          <ol>
            <li>Joined the organization</li>
            <li>Designation: HR Manager</li>
            <li>Moved to People Operations</li>
          </ol>
        </div>
      </div>
    )
  }

  if (type === 'team') {
    return (
      <div className="pgs-viz pgs-viz-team" aria-hidden="true">
        <div className="pgs-viz-card">
          <strong>Team Strength: 127</strong>
          <p>Alabama - 80 · Chicago - 47</p>
        </div>
        <div className="pgs-viz-card">
          <strong>Madison Harris</strong>
          <p>Shared an update with the department wall.</p>
        </div>
        <div className="pgs-viz-card">
          <strong>New Hires</strong>
          <p>Sophia Campbell · Ethan Johnson</p>
        </div>
      </div>
    )
  }

  if (type === 'settings') {
    return (
      <div className="pgs-viz pgs-viz-settings" aria-hidden="true">
        <div className="pgs-viz-org">
          <i>P</i>
          <div>
            <strong>Pulse Org</strong>
            <span>Enterprise · Active users</span>
          </div>
        </div>
        <div className="pgs-viz-grid">
          {[
            [GearSix, 'Manage Account'],
            [UsersThree, 'Employee Information'],
            [ClipboardText, 'Marketplace'],
            [ChartBar, 'Developer Space'],
          ].map(([Icon, label]) => (
            <div key={label} className="pgs-viz-card">
              <Icon size={18} weight="duotone" />
              <strong>{label}</strong>
            </div>
          ))}
        </div>
      </div>
    )
  }

  return null
}

const PORTAL_MIN = 6
const PORTAL_MAX = 50
const PORTAL_LEN_MSG = 'Portal name must have minimum of 6 and maximum of 50 characters'
const PORTAL_EXISTS_MSG = 'This Portal Name already exists'

function portalLengthError(portalId) {
  const len = String(portalId || '').trim().length
  if (len === 0) return ''
  if (len < PORTAL_MIN || len > PORTAL_MAX) return PORTAL_LEN_MSG
  return ''
}

export default function PulseGettingStarted() {
  const { user, loading, updateProfile } = useAuth()
  const navigate = useNavigate()
  const { portalId: portalParam } = useParams()
  const [modalOpen, setModalOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const [sampleBusy, setSampleBusy] = useState(false)
  const [step, setStep] = useState(null)
  const [slide, setSlide] = useState(0)
  const [portalTouched, setPortalTouched] = useState(false)
  const [portalError, setPortalError] = useState('')
  const initialPortalRef = useRef('')
  const repairedPortalRef = useRef(false)
  const savedRef = useRef((() => {
    try {
      if (sessionStorage.getItem('pulseJustSaved') === '1') {
        sessionStorage.removeItem('pulseJustSaved')
        return true
      }
    } catch {
      /* ignore */
    }
    return false
  })())
  const [form, setForm] = useState({
    companyName: '',
    portalId: '',
    industry: '',
    employeeCount: '',
  })

  // Refresh Pulse flags from the server without blocking the page.
  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        const res = await api.get('/auth/profile', { __skipCache: true })
        if (cancelled || !res?.data?.user) return
        const next = res.data.user
        if (next.pulseSetupCompleted === true || hasPulseAccount(next)) {
          markPulseAccountCreated(next.pulsePortalId)
        }
        if (savedRef.current) {
          updateProfile({
            ...next,
            pulseSetupCompleted: true,
            pulsePortalId: next.pulsePortalId || '',
          })
          return
        }
        updateProfile(next)
      } catch {
        /* keep session user */
      }
    })()
    return () => {
      cancelled = true
    }
  }, [updateProfile])

  // Replace timestamp-style portal IDs with the company-based portal name.
  useEffect(() => {
    if (!user?.pulseSetupCompleted || repairedPortalRef.current) return
    if (!isAutoGeneratedPortalId(user.pulsePortalId)) return
    const nextPortal = suggestPulsePortalId(user)
    if (!nextPortal || nextPortal.length < PORTAL_MIN || isAutoGeneratedPortalId(nextPortal)) return
    repairedPortalRef.current = true
    ;(async () => {
      try {
        const res = await api.post('/auth/pulse-setup', {
          companyName: user.companyName || nextPortal,
          portalId: nextPortal,
          industry: user.industry || 'Other',
          employeeCount: user.pulseEmployeeCount || '1',
        })
        const nextUser = {
          ...res.data.user,
          pulseSetupCompleted: true,
          pulsePortalId: nextPortal,
        }
        markPulseAccountCreated(nextPortal)
        updateProfile(nextUser)
        navigate(getPulseGettingStartedPath(nextUser), { replace: true })
      } catch {
        repairedPortalRef.current = false
      }
    })()
  }, [user, updateProfile, navigate])

  useEffect(() => {
    if (!user) return
    const accountReady = savedRef.current || hasPulseAccount(user)

    if (accountReady) {
      const expected = getPulseGettingStartedPath(user)
      const current = window.location.pathname.replace(/\/+$/, '')
      if (current !== expected.replace(/\/+$/, '')) {
        navigate(expected, { replace: true })
      }
      setModalOpen(false)
      if (savedRef.current) {
        setStep((s) => (s === 'guide' ? 'guide' : 'sample'))
        return
      }
      if (needsPulseGettingStartedGuide() || getPulseSampleChoice() === '0') {
        setStep('guide')
        return
      }
      if (getPulseSampleChoice() === '1') {
        navigate(PULSE_HOME, { replace: true })
        return
      }
      setStep('sample')
      return
    }
    // Never keep auto-generated numeric IDs in the URL.
    if (portalParam && (isReservedPortalSegment(portalParam) || isAutoGeneratedPortalId(portalParam))) {
      navigate('/pulse/settings/service/getting-started', { replace: true })
    }
    setStep('company')
    setModalOpen(true)
    const starter = suggestPulsePortalId({
      ...user,
      pulsePortalId:
        user.pulsePortalId && !isAutoGeneratedPortalId(user.pulsePortalId)
          ? user.pulsePortalId
          : portalParam && !isAutoGeneratedPortalId(portalParam)
            ? portalParam
            : '',
    })
    initialPortalRef.current = starter
    setPortalTouched(false)
    setPortalError('')
    setForm({
      companyName: user.companyName || '',
      portalId: starter,
      industry: user.industry || '',
      employeeCount: user.pulseEmployeeCount || '',
    })
  }, [user, navigate, portalParam])

  const closeGettingStarted = () => {
    if (savedRef.current || hasPulseAccount(user)) {
      if (!hasPulseSampleChoice() || needsPulseGettingStartedGuide() || getPulseSampleChoice() === '0') {
        setModalOpen(false)
        setStep(getPulseSampleChoice() === '0' || needsPulseGettingStartedGuide() ? 'guide' : 'sample')
        return
      }
      navigate(PULSE_HOME)
      return
    }
    navigate('/pulse')
  }

  const leaveGuide = () => {
    dismissPulseGuide()
    navigate(PULSE_HOME)
  }

  const finishSampleChoice = (value) => {
    if (sampleBusy) return
    setSampleBusy(true)
    try {
      localStorage.setItem('pulseSampleData', value)
    } catch {
      /* ignore */
    }
    if (value === '1') {
      dismissPulseGuide()
      toast.success('Sample data will appear as you explore Pulse.')
      window.setTimeout(() => navigate(PULSE_HOME, { replace: true }), 450)
      return
    }
    setSampleBusy(false)
    setSlide(0)
    setStep('guide')
  }

  const onCompanyChange = (companyName) => {
    const fromCompany = portalIdFromCompanyName(companyName)
    const nextPortal = portalTouched
      ? form.portalId
      : fromCompany || initialPortalRef.current
    setForm((f) => ({
      ...f,
      companyName,
      portalId: nextPortal,
    }))
    if (portalError) setPortalError('')
  }

  const onPortalChange = (portalId) => {
    const next = normalizePulsePortalId(portalId).slice(0, PORTAL_MAX) || portalId.slice(0, PORTAL_MAX)
    setPortalTouched(true)
    setForm((f) => ({ ...f, portalId: next }))
    if (portalError) setPortalError('')
  }

  const onSave = async (e) => {
    e.preventDefault()
    if (saving) return
    if (!form.companyName.trim()) {
      toast.error('Enter company name.')
      return
    }
    let portal = normalizePulsePortalId(form.portalId.trim())
    if (!portal || isAutoGeneratedPortalId(portal)) {
      portal = portalIdFromCompanyName(form.companyName)
    }
    if (!portal) {
      setPortalError(PORTAL_LEN_MSG)
      return
    }
    if (isReservedPortalSegment(portal)) {
      setPortalError('This Portal Name is reserved. Choose another.')
      return
    }
    const lenErr = portalLengthError(portal)
    if (lenErr) {
      setPortalError(lenErr)
      return
    }
    if (!form.industry) {
      toast.error('Select an industry.')
      return
    }
    if (!form.employeeCount.trim()) {
      toast.error('Enter employee count.')
      return
    }
    setSaving(true)
    try {
      const res = await api.post('/auth/pulse-setup', {
        companyName: form.companyName.trim(),
        portalId: portal,
        industry: form.industry,
        employeeCount: form.employeeCount.trim(),
      })
      const nextUser = { ...res.data.user, pulseSetupCompleted: true, pulsePortalId: portal }
      savedRef.current = true
      try {
        sessionStorage.setItem('pulseJustSaved', '1')
      } catch {
        /* ignore */
      }
      markPulseAccountCreated(portal)
      updateProfile(nextUser)
      setModalOpen(false)
      setStep('sample')
      setSaving(false)
      const nextPath = getPulseGettingStartedPath(nextUser)
      const current = window.location.pathname.replace(/\/+$/, '')
      if (current !== nextPath.replace(/\/+$/, '')) {
        navigate(nextPath, { replace: true })
      }
    } catch (err) {
      const msg = err.response?.data?.message || 'Could not save Pulse account'
      const code = err.response?.data?.code
      if (code === 'PORTAL_EXISTS' || /already exists/i.test(msg)) {
        setPortalError(PORTAL_EXISTS_MSG)
      } else if (code === 'PORTAL_LENGTH' || /minimum of 6/i.test(msg)) {
        setPortalError(PORTAL_LEN_MSG)
      } else {
        toast.error(msg)
      }
      setSaving(false)
    }
  }

  if (loading || !user || !step) {
    return <PulseLoading />
  }

  if (
    hasPulseAccount(user) &&
    hasPulseSampleChoice() &&
    !needsPulseGettingStartedGuide() &&
    step !== 'guide' &&
    step !== 'sample'
  ) {
    return <PulseLoading label="Opening Pulse..." />
  }

  if (step === 'sample') {
    return (
      <div className="pgs-page is-sample-step">
        <PulseSampleDataStep
          busy={sampleBusy}
          onYes={() => finishSampleChoice('1')}
          onNo={() => finishSampleChoice('0')}
        />
        <PulseSmartChat />
      </div>
    )
  }

  const active = SLIDES[slide] || SLIDES[0]
  const isGuide = step === 'guide'

  return (
    <div className={`pgs-page${isGuide ? ' is-guide' : ''}`}>
      {!isGuide ? (
        <header className="pgs-top">
          <h1>Getting Started</h1>
          <div className="pgs-top-actions">
            <PulseAppearanceToggle />
            <button type="button" className="pgs-close" aria-label="Close" onClick={closeGettingStarted}>
              ×
            </button>
          </div>
        </header>
      ) : null}

      <div className="pgs-shell">
        <div className="pgs-frame">
          {isGuide ? (
            <header className="pgs-top is-in-frame">
              <h1>Getting Started</h1>
              <div className="pgs-top-actions">
                <PulseAppearanceToggle />
                <button type="button" className="pgs-close" aria-label="Close" onClick={leaveGuide}>
                  ×
                </button>
              </div>
            </header>
          ) : null}

          <div className="pgs-body">
            <div className="pgs-stage">
              <div className="pgs-panels">
              <section className={`pgs-intro pgs-panel-card pgs-slide-${active.kind}`} key={active.id}>
                <div className="pgs-intro-main">
                  {active.kind === 'intro' ? <PulseVersionHero /> : null}
                  <h2>{active.title}</h2>
                  <p>{active.body}</p>
                  {active.visual ? <SlideVisual type={active.visual} /> : null}
                </div>

                <div className="pgs-slide-nav">
                  <div className="pgs-dots" role="tablist" aria-label="Getting started slides">
                    {SLIDES.map((item, i) => (
                      <button
                        key={item.id}
                        type="button"
                        role="tab"
                        aria-selected={i === slide}
                        className={i === slide ? 'is-on' : undefined}
                        onClick={() => setSlide(i)}
                      />
                    ))}
                  </div>
                  <div className="pgs-slide-links">
                    {slide > 0 ? (
                      <button type="button" onClick={() => setSlide((s) => Math.max(0, s - 1))}>
                        Previous
                      </button>
                    ) : null}
                    {slide > 0 && slide < SLIDES.length - 1 ? <span aria-hidden="true"> | </span> : null}
                    {slide < SLIDES.length - 1 ? (
                      <button
                        type="button"
                        onClick={() => setSlide((s) => Math.min(SLIDES.length - 1, s + 1))}
                      >
                        Next
                      </button>
                    ) : null}
                  </div>
                </div>
              </section>

              <aside className="pgs-checklist pgs-panel-card">
                <h3>Let&apos;s begin!</h3>
                <p className="pgs-check-kicker">Follow our recommended workflow to get started.</p>
                <ol>
                  {WORKFLOW.map((item) => (
                    <li key={item.title}>
                      <button
                        type="button"
                        className="pgs-step-row"
                        onClick={() => {
                          if (!isGuide) setModalOpen(true)
                          else toast('Open this from Settings after you enter Pulse.')
                        }}
                      >
                        <WorkflowCheckIcon />
                        <span className="pgs-step-copy">
                          <span className="pgs-step-link">{item.title}</span>
                          <span className="pgs-step-desc">{item.desc}</span>
                        </span>
                      </button>
                    </li>
                  ))}
                </ol>
              </aside>
              </div>
            </div>
          </div>

          <footer className="pgs-foot">
            <button
              type="button"
              className="pgs-get-started"
              onClick={() => (isGuide ? leaveGuide() : setModalOpen(true))}
            >
              Get Started
            </button>
          </footer>
        </div>
      </div>

      {!isGuide && modalOpen ? (
        <div className="pgs-modal-root" role="presentation">
          <button
            type="button"
            className="pgs-modal-backdrop"
            aria-label="Close dialog"
            onClick={() => !saving && setModalOpen(false)}
          />
          <form
            className="pgs-modal"
            role="dialog"
            aria-modal="true"
            aria-labelledby="pgs-modal-title"
            onSubmit={onSave}
          >
            <header className="pgs-modal-head">
              <h2 id="pgs-modal-title">Company Information</h2>
              <p className="pgs-modal-sub">Help us setup your account</p>
            </header>

            <div className="pgs-modal-card">
              <label>
                <span className="pgs-label-text">
                  Company name <i className="pgs-req" aria-hidden="true">
                    *
                  </i>
                </span>
                <input
                  value={form.companyName}
                  onChange={(e) => onCompanyChange(e.target.value)}
                  required
                  autoFocus
                />
              </label>
              <label>
                <span className="pgs-label-text">
                  Portal Name <i className="pgs-req" aria-hidden="true">
                    *
                  </i>
                </span>
                <input
                  value={form.portalId}
                  onChange={(e) => onPortalChange(e.target.value)}
                  className={portalError ? 'is-invalid' : undefined}
                  maxLength={PORTAL_MAX}
                />
                {portalError ? <span className="pgs-field-error">{portalError}</span> : null}
              </label>
              <div className="pgs-field">
                <span className="pgs-label-text">
                  Industry <i className="pgs-req" aria-hidden="true">
                    *
                  </i>
                </span>
                <IndustrySelect
                  value={form.industry}
                  disabled={saving}
                  onChange={(industry) => setForm((f) => ({ ...f, industry }))}
                />
              </div>
              <label>
                <span className="pgs-label-text">
                  Employee Count <i className="pgs-req" aria-hidden="true">
                    *
                  </i>
                </span>
                <input
                  value={form.employeeCount}
                  onChange={(e) => setForm((f) => ({ ...f, employeeCount: e.target.value }))}
                  required
                />
              </label>
            </div>

            <footer className="pgs-modal-foot">
              <button type="submit" className="pgs-save" disabled={saving}>
                {saving ? (
                  <span className="pgs-save-busy">
                    <i className="pgs-save-ring" aria-hidden="true" />
                    Saving...
                  </span>
                ) : (
                  'Save'
                )}
              </button>
            </footer>
          </form>
        </div>
      ) : null}
      <PulseSmartChat />
    </div>
  )
}
