const PULSE_GETTING_STARTED_SUFFIX = '/settings/service/getting-started'

/** Paths that must never be treated as a portal name. */
const RESERVED_PORTAL_SEGMENTS = new Set([
  'login',
  'register',
  'account',
  'apps',
  'portal',
  'pulse',
  'people',
  'setup',
  'oauth',
  'coming-soon',
  'smart-signin',
  'people-os',
  'dashboard',
  'staff',
  'payslips',
  'performance',
  'attendance',
  'leave',
  'settings',
  'tasks',
  'forgot',
  'reset-password',
  'verify',
  'verify-email',
  'api',
])

export const PULSE_HOME = '/pulse/home'

const PULSE_SKIP_REMEMBER = new Set([
  '/pulse',
  '/pulse/getting-started',
  `/pulse${PULSE_GETTING_STARTED_SUFFIX}`,
])

export function normalizePulsePortalId(portalId) {
  return String(portalId || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, '')
    .slice(0, 50)
}

/** Timestamp-style auto IDs like 86972825350 - never use these as portal names. */
export function isAutoGeneratedPortalId(portalId) {
  const id = String(portalId || '').trim()
  return /^\d{6,}$/.test(id)
}

export function portalIdFromCompanyName(companyName) {
  return normalizePulsePortalId(companyName)
}

export function suggestPulsePortalId(user) {
  const existing = normalizePulsePortalId(user?.pulsePortalId)
  if (existing && !isAutoGeneratedPortalId(existing) && !isReservedPortalSegment(existing)) {
    return existing
  }
  const fromCompany = portalIdFromCompanyName(user?.companyName)
  if (fromCompany.length >= 6) return fromCompany
  const fromEmail = normalizePulsePortalId(String(user?.email || '').split('@')[0])
  if (fromEmail.length >= 6) return fromEmail
  return fromCompany || fromEmail || ''
}

export function isReservedPortalSegment(segment) {
  const id = normalizePulsePortalId(segment)
  return !id || RESERVED_PORTAL_SEGMENTS.has(id)
}

/** Pulse path: /{portalName}/settings/service/getting-started */
export function getPulseGettingStartedPath(userOrPortalId) {
  if (userOrPortalId && typeof userOrPortalId === 'object') {
    const portalId = suggestPulsePortalId(userOrPortalId)
    if (!portalId || isReservedPortalSegment(portalId)) {
      return `/pulse${PULSE_GETTING_STARTED_SUFFIX}`
    }
    return `/${portalId}${PULSE_GETTING_STARTED_SUFFIX}`
  }

  const portalId = normalizePulsePortalId(userOrPortalId)
  if (!portalId || isReservedPortalSegment(portalId) || isAutoGeneratedPortalId(portalId)) {
    return `/pulse${PULSE_GETTING_STARTED_SUFFIX}`
  }
  return `/${portalId}${PULSE_GETTING_STARTED_SUFFIX}`
}

/** @deprecated use getPulseGettingStartedPath(user) */
export const PULSE_GETTING_STARTED = `/pulse${PULSE_GETTING_STARTED_SUFFIX}`

export function hasPulseSampleChoice() {
  try {
    return localStorage.getItem('pulseSampleData') != null
  } catch {
    return false
  }
}

export function getPulseSampleChoice() {
  try {
    return localStorage.getItem('pulseSampleData')
  } catch {
    return null
  }
}

export function hasPulseGuideDismissed() {
  try {
    return localStorage.getItem('pulseGuideDismissed') === '1'
  } catch {
    return false
  }
}

export function dismissPulseGuide() {
  try {
    localStorage.setItem('pulseGuideDismissed', '1')
  } catch {
    /* ignore */
  }
}

/** Allow returning to Getting Started from /pulse. */
export function reopenPulseGuide() {
  try {
    localStorage.removeItem('pulseGuideDismissed')
  } catch {
    /* ignore */
  }
}

/** Clear local Pulse onboarding flags (sample choice / last path). */
export function clearPulseLocalState() {
  try {
    localStorage.removeItem('pulseSampleData')
    localStorage.removeItem('pulseLastPath')
    localStorage.removeItem('pulseGuideDismissed')
  } catch {
    /* ignore */
  }
}

/** True when own-data users still need the Getting Started hub. */
export function needsPulseGettingStartedGuide() {
  return getPulseSampleChoice() === '0' && !hasPulseGuideDismissed()
}

function isGettingStartedPath(path) {
  return typeof path === 'string' && path.endsWith(PULSE_GETTING_STARTED_SUFFIX)
}

export function markPulseAccountCreated(portalId) {
  try {
    localStorage.setItem('pulseAccountCreated', normalizePulsePortalId(portalId) || '1')
  } catch {
    /* ignore */
  }
}

/** Pulse company account already exists (server flag, portal id, or local save). */
export function hasPulseAccount(user) {
  if (user?.pulseSetupCompleted === true) return true
  const portalId = normalizePulsePortalId(user?.pulsePortalId)
  if (portalId && !isAutoGeneratedPortalId(portalId) && !isReservedPortalSegment(portalId)) {
    return true
  }
  try {
    return !!localStorage.getItem('pulseAccountCreated')
  } catch {
    return false
  }
}

/** Where to open Pulse from the apps launcher / deep links. */
export function getPulseOpenPath(user) {
  if (!hasPulseAccount(user)) return '/pulse'
  if (!hasPulseSampleChoice() || needsPulseGettingStartedGuide()) {
    return getPulseGettingStartedPath(user)
  }

  try {
    const last = localStorage.getItem('pulseLastPath')
    if (
      last &&
      last.startsWith('/') &&
      last !== '/pulse' &&
      !PULSE_SKIP_REMEMBER.has(last) &&
      !isGettingStartedPath(last)
    ) {
      return last
    }
  } catch {
    /* ignore */
  }

  return PULSE_HOME
}

/** After company login / OAuth — land on Accounts. */
export function getPostLoginPath() {
  return '/account'
}

/** Remember last Pulse screen so reopen resumes there. */
export function rememberPulsePath(pathname) {
  if (!pathname) return
  const path = pathname.replace(/\/+$/, '') || '/'
  if (PULSE_SKIP_REMEMBER.has(path) || isGettingStartedPath(path)) return
  if (!(path.startsWith('/pulse') || /^\/[^/]+\/settings\//.test(path))) return
  try {
    localStorage.setItem('pulseLastPath', path)
  } catch {
    /* ignore */
  }
}
